// Wires `/api/openapi.json` and `/api/docs` (Swagger UI via CDN) onto the
// Hono app. Skipped in prod via the shared `isProduction` helper — accepts
// both `NODE_ENV=production` and `NODE_ENV=prod` (the value the CDK stack
// actually sets, see `infra/lib/api-stack.ts` `NODE_ENV: config.stage`).
//
// The JSON file is read once and cached in module scope. `pnpm dev` runs from
// `apps/backend/`, so the resolved path matches the file generated by
// `pnpm --filter @kaipos/backend openapi:generate`.
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Hono } from 'hono';
import { isProduction } from '../lib/env.js';
import type { AppEnv } from '../types.js';

const here = dirname(fileURLToPath(import.meta.url));
const openapiPath = resolve(here, '../../openapi.json');

let cached: string | null = null;

function loadOpenApiJson(): string {
  if (cached) return cached;
  cached = readFileSync(openapiPath, 'utf8');
  return cached;
}

const SWAGGER_HTML = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>KaiPOS API — Swagger UI</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swagger-ui-dist@5.17.14/swagger-ui.css" />
  </head>
  <body>
    <div id="swagger-ui"></div>
    <script src="https://cdn.jsdelivr.net/npm/swagger-ui-dist@5.17.14/swagger-ui-bundle.js" crossorigin></script>
    <script>
      window.addEventListener('load', () => {
        window.ui = SwaggerUIBundle({
          url: '/api/openapi.json',
          dom_id: '#swagger-ui',
          deepLinking: true,
        });
      });
    </script>
  </body>
</html>`;

export function registerDocsRoutes(app: Hono<AppEnv>): void {
  if (isProduction) return;

  app.get('/api/openapi.json', (c) => {
    const body = loadOpenApiJson();
    return c.body(body, 200, { 'content-type': 'application/json; charset=utf-8' });
  });

  app.get('/api/docs', (c) => c.html(SWAGGER_HTML));
}
